name: Lint & Format

on:
  pull_request:
  push:
    branches: [ main, master, develop, "**/*" ]

jobs:
  style-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Verifica formato; falla si hay archivos sin formatear
      - name: Prettier (check)
        run: npm run format:check

      # Linter; muestra anotaciones en el PR
      - name: ESLint
        run: npm run lint
